name: Có người mở Issue!
on:
  issues:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Có người mở issue nè cha - ${{ github.event.issue.title }}"}' $YOUR_WEBHOOK_URL
        env:
          YOUR_WEBHOOK_URL: ${{ secrets.YOUR_WEBHOOK_URL }}
          
