name: issue created
on:
  issues:
    types: [opened, edited, milestoned]
    

jobs:
  update-notebooks:
    runs-on: ubuntu-latest
    steps:
  
    - name: See event name
      run: |
        echo "path: ${{ GITHUB_EVENT_PATH }}"
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}
